server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: http://localhost:9898
          predicates:
            - Path=/api/**
        - id: eurekaserver
          uri: lb://EUREKASERVER
          predicates:
            - Path=/eurekaserver/**

