server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: payment-ms
          uri: http://localhost:9090
          predicates:
            - Path=/api/v2/**
          filters:
            - name: RemoveRequestHeader
              args:
                name: Authorization
        - id: security-ms
          uri: http://localhost:9898
          predicates:
            - Path=/api/**
        - id: eurekaserver
          uri: lb://EUREKASERVER
          predicates:
            - Path=/eurekaserver/**
logging:
  level:
    root: debug
