spring:
  application:
    name: payment-ms

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 9090

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
#
#logging:
#  level:
#    root: debug